// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSXlNa9QNrPieO97cDKy2FSsh-WLKyZfw',
    appId: '1:206631465514:web:b35123359d03fea2f94953',
    messagingSenderId: '206631465514',
    projectId: 'signatureapp-ea708',
    authDomain: 'signatureapp-ea708.firebaseapp.com',
    storageBucket: 'signatureapp-ea708.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr3EBIAM9kV8TcvsfyTcOUZFPJ_j97f8U',
    appId: '1:206631465514:android:546e2f9979f4b3a0f94953',
    messagingSenderId: '206631465514',
    projectId: 'signatureapp-ea708',
    storageBucket: 'signatureapp-ea708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi3_MUOyf0foDEj5HgQhKnued1-1os-94',
    appId: '1:206631465514:ios:61c9969cede38497f94953',
    messagingSenderId: '206631465514',
    projectId: 'signatureapp-ea708',
    storageBucket: 'signatureapp-ea708.appspot.com',
    iosClientId: '206631465514-23c4gomtrpqunvd6csghhsimhogkd53d.apps.googleusercontent.com',
    iosBundleId: 'com.example.signatureapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi3_MUOyf0foDEj5HgQhKnued1-1os-94',
    appId: '1:206631465514:ios:61c9969cede38497f94953',
    messagingSenderId: '206631465514',
    projectId: 'signatureapp-ea708',
    storageBucket: 'signatureapp-ea708.appspot.com',
    iosClientId: '206631465514-23c4gomtrpqunvd6csghhsimhogkd53d.apps.googleusercontent.com',
    iosBundleId: 'com.example.signatureapp',
  );
}
